services:
  - type: web
    name: resume-matcher
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn appv9:app
    envVars:
      - key: FLASK_ENV
        value: production
